### ISSUE TITLE
the information insert lines

### ISSUE THREAD

**Issue by bodnarlajos** [emacs-sideline/sideline#7]
Hi,
first of all thanks for this mode!
When I enable it the error infromation will insert lines to the code.
In this case the information will push the original code down!

Can I do something with it ?

**Comment by jcs090218** [comment]
It shouldn't be inserting anything. What is your config regarding this mode?

**Comment by bodnarlajos** [comment]
I just use with the default configuration. The backends are lsp and flymake.

**Comment by jcs090218** [comment]
I don't think any of these backend will cause insertion. Can you provide a screenshot or gif? 😕

**Comment by jcs090218** [comment]
Make sure you try it with `emacs -q`, may be there is something wrong with your configuration.

**Comment by bodnarlajos** [comment]
Here is two screenshot and I'll come back to you with the result of my testing ...
https://imgur.com/a/QTFWkvf

thanks in advance

**Comment by jcs090218** [comment]
Do you mean those red/green lines? It seems like the message from flymake is extremely long and contains newlines which causes one or more lines is presented! This isn't a big but it could be very annoying...

**Comment by bodnarlajos** [comment]
Yes, I'was thinking about those lines.
You can close this issue if you want, I just would have liked to mention it ...
Thanks for you time :)

**Comment by Yuanda-Dong** [comment]
Hi, 
I had a similar issue, where the flycheck message contained newlines. I was able to format the error message by using "%.80s", so that it never exceeds 80 characters, but i don't think it's possible to strip newline characters using the `format` function. 
I'm new to writing Emacs lisp, but maybe allowing user to run a customizable function on the text itself would help, and make the functionalities more extensible. 

![image](https://user-images.githubusercontent.com/37124273/229361223-c6569df5-d3dd-48f6-b57e-837d77974c98.png)

**Comment by jcs090218** [comment]
I've implemented this feature, see backends' customization section:

- https://github.com/emacs-sideline/sideline-flycheck#-customization
- https://github.com/emacs-sideline/sideline-flymake#-customization

**Comment by jcs090218** [comment]
I think we've a solution? Closing this now! Thanks! ;)

**Comment by bodnarlajos** [comment]
Thanks! Very good news, I'll check it asap!
